name: CI/CD Pipeline for Nginx Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Build and Push Docker Image to Registry
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Verify Docker Buildx setup
        run: |
          docker buildx version
          docker buildx ls

      - name: Check if Dockerfile exists
        run: |
          ls -la
          if [ ! -f "Dockerfile" ]; then
            echo "ERROR: Dockerfile not found in the repository!"
            exit 1
          fi

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --platform linux/amd64 --tag shilpigoyal729/nginx-app:${{ github.sha }} --push .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

  # Step 2: Deploy to Kubernetes
  deploy_to_kubernetes:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

      - name: Configure kubectl
        run: |
          kubectl config set-cluster my-cluster --server=${{ secrets.K8S_API_SERVER }}
          kubectl config set-credentials my-user --token=${{ secrets.K8S_TOKEN }}
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context

      - name: Deploy to Kubernetes
        run: |
          export GITHUB_SHA=${{ github.sha }}
          cat deployment.yml | envsubst | kubectl apply -f -
          kubectl rollout status deployment/nginx-deployment
